### ISSUE TITLE
Tabele: vrstni red regij

### ISSUE THREAD

**Issue by lukarenko** [slo-covid-19/website#124]
![image](https://user-images.githubusercontent.com/46861689/78220976-ccff9200-74c2-11ea-8200-3f52bd28031d.png)

Regije bi bilo dobro sortirati: ali po imenu ali pa po številu okuženih (od najbolj do najmanj)

**Comment by VesterDe** [comment]
Raje po imenu, po stevilu bi bil kaos ker bi se konstantno menjale...
