### ISSUE TITLE
UX: Grafi - kumulativa (todate) dotted_line, trenutno/nadab (daily) solid_line

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#125]
na grafih bi radi poenotili (spremenili) vse metrike, ki so kumulativne (skupaj, vsi, todate) od tistih, ki so za trenuten dan  tako da bi todate metrike vedno risali z črtkanimi črtami, dnevne pa z polno črto, ker so bolj dinamične.

**Comment by lukarenko** [comment]
@matejmeglic mislim, da mora biti ravno obratno, saj bo dnevna, ki je bolj dinamična čudno izpadla v kratkih obratih? A je kakšen dober razlog?

**Comment by matejmeglic** [comment]
implementiramo tako, kot si rekel - samo napačno sem prebral vse skupi. Sem popravil naslov.

**Comment by lukarenko** [comment]
@matejmeglic A lahko to dodamo tudi na graf Hospitalizirani?
Ali lahko tudi poenotimo oznako, da so recimo vsi črtkani romb in square?

**Comment by matejmeglic** [comment]
sem že gledal, pa v 5tih minutah nisem našel enostavnega fixa za graf Hospitalizirani (PatientsCharts), kot je bil za MetricComparisonChart.

Oznaka (ki se trenutno spreminja za vsako črto) se s HighCharts kot kaže izračuna samodejno (in je zaenkrat unique), tako da bi se verjetno dalo popravit, je pa najbrž out-of-reach za moje znanje.

**Comment by lukarenko** [comment]
Popravil tudi za PatientsChart
