### ISSUE TITLE
"Po dnevih" bi moral biti default pri grafu "Struktura potrjeno okuženih"

### ISSUE THREAD

**Issue by tomazk** [slo-covid-19/website#161]
Predlagam da spremenimo default iz "skupaj" na "po dnevih". Graf "po dnevih" je veliko bolj informativen, saj obiskovalca spletne strani direktno informira o spreminjajoči se strukturi potrjeno okuženih.

![FireShot Capture 020 - COVID-19 Sledilnik - covid-19 sledilnik org](https://user-images.githubusercontent.com/83787/78508632-98bcf780-7788-11ea-8e2b-0dc55808838c.png)

Če se ne strnijate, zaprem issue in lahko debato premaknemo na slack.

**Comment by lukarenko** [comment]
Se strinjam

**Comment by lukarenko** [comment]
Done by @pkese
