### ISSUE TITLE
Embed: dodati branding

### ISSUE THREAD

**Issue by lukarenko** [slo-covid-19/website#177]
Trenutno imamo nekaj že pripravljenih embed strani:

**Grafi:**
https://covid-19.sledilnik.org/embed.html#/chart/MetricsComparison
https://covid-19.sledilnik.org/embed.html#/chart/Patients
https://covid-19.sledilnik.org/embed.html#/chart/Infections
https://covid-19.sledilnik.org/embed.html#/chart/Spread
https://covid-19.sledilnik.org/embed.html#/chart/Regions
https://covid-19.sledilnik.org/embed.html#/chart/Map
https://covid-19.sledilnik.org/embed.html#/chart/Municipalities
https://covid-19.sledilnik.org/embed.html#/chart/AgeGroups

https://covid-19.sledilnik.org/embed.html#/chart/Hospitals  (internal use only!)

**Dashboard:**
https://covid-19.sledilnik.org/embed.html#/card/confirmedCases
https://covid-19.sledilnik.org/embed.html#/card/hospitalized
https://covid-19.sledilnik.org/embed.html#/card/icu
https://covid-19.sledilnik.org/embed.html#/card/deceased
https://covid-19.sledilnik.org/embed.html#/card/recovered

**Tabela:**
https://covid-19.sledilnik.org/embed.html#/tables

Rabimo pa na stran dati logo (mobile, narrow screen) oz.znak (wide screen), zato da imamo branding in povezavo nazaj na našo glavno stran. Tukaj je en predlog od Jureta:
![Screen Shot 2020-04-05 at 19 37 56](https://user-images.githubusercontent.com/46861689/78863193-43f3d800-7a39-11ea-8610-7aa16f264bc2.png)

**Comment by mitjapotocin** [comment]
Grafi: done in #180

**Comment by lukarenko** [comment]
@mitjapotocin ostalo niti ni tako nujno. Za InfoCard se mi tako zdi, da bi bilo mogoče bolje, če bi imeli en embed za vse InfoCard skupaj.

**Comment by lukarenko** [comment]
Jaz bom ta issue kar zaprl in bomo raje odprli nov issue za preostale zadeve (ki niso tako nujne)
