### ISSUE TITLE
Embed: možnost parametrizacije pogleda za Municipalities

### ISSUE THREAD

**Issue by lukarenko** [slo-covid-19/website#184]
Za Embed graf za občine bi bilo super, če bi lahko preko URL specificiral privzeti pogled za filter:
https://covid-19.sledilnik.org/embed.html#/chart/Municipalities

Recimo:
https://covid-19.sledilnik.org/embed.html#/chart/Municipalities?region=LJ
https://covid-19.sledilnik.org/embed.html#/chart/Municipalities?region=KK&sort=time-to-double

Tako bi lahko na regionalni portal dali privzeti pogled samo na njihovo pokrajino.

**Comment by joahim** [comment]
Parametri:

`sort=`
- `total-positive-tests`
- `time-to-double`

`region=`
- `ms` (Pomurska)
- `mb` (Podravska)
- `sg` (Koroška)
- `ce` (Savinjska)
- `za` (Zasavska)
- `kk` (Posavska)
- `nm` (Jugovzhodna Slovenija)
- `lj` (Osrednjeslovenska)
- `kr` (Gorenjska)
- `po` (Primorsko-notranjska)
- `ng` (Goriška)
- `kp` (Obalno-kraška)
