### ISSUE TITLE
Vizualizacija - https://behroozh.shinyapps.io/COVID19/ - ali lahko to avtomatiziramo?

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#21]
https://behroozh.shinyapps.io/COVID19/ 
https://www.dropbox.com/s/y4ng6vkfbxeeoj0/Screenshot%202020-03-24%2010.16.01.png?dl=0
- baje nekaj podobnega imamo na alpaki,
- komentar Maksa celo normalizirano na število prebivalcev, ampak mislim da mu fali zamik (lag) za posamezno državo ?

**Comment by pkese** [comment]
paste prilepljenega sampla:
![image](https://user-images.githubusercontent.com/278492/77583138-d7c59000-6ee0-11ea-9ce4-47aa01c727e2.png)

A so ti podatki kje na voljo?

**Comment by mkadunc** [comment]
Podatki v appu so (verjetno) iz https://github.com/CSSEGISandData/COVID-19

Sicer je pa (baje boljsi) dataset na voljo tudi od ECDC: https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

**Comment by matejmeglic** [comment]
Baje, da ima Nace na Alpaki tole že potrackano - mislim da gre za vizualizacijo Širjenje COVID-19 (okužbe / število prebivalcev) / Log Y

![image](https://user-images.githubusercontent.com/26248400/77592558-af469180-6ef2-11ea-9e37-104855003c9b.png)

**Comment by matejmeglic** [comment]
Zapiram, ker v 3h tednih ni bilo interesa. Se lahko ponovno odpre.
