### ISSUE TITLE
Vizualizacija - primerjava z Italijo 

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#23]
kot https://i.redd.it/vyaoukcj5un41.png

**Comment by pkese** [comment]
Primerjava z Italijo daje lažen občutek varnosti.

Če se že s kom primerjamo, se dajmo z Južno Korejo.

**Comment by matejmeglic** [comment]
issue potrebuje dodatno debato preden nekdo vlaga preveč notr. Jst tuki nism dovolj avtoritete, da bi lahko odločal o tem. @lukarenko

**Comment by matejmeglic** [comment]
Ni relevantno, situacije so preveč različne, ni interesa. zapiram.
