### ISSUE TITLE
Padding na strani O projektu

### ISSUE THREAD

**Issue by joahim** [slo-covid-19/website#55]
Na mobile stran nima paddinga in se besedeilo zažre v rob.

**Comment by overlordtm** [comment]
Lahko screenshot? Meni na firefox/chrome @ android dela OK. Je pa druig problem, odkar imamo fixed navbar, ko zamenjas stran te ne zascrolla navrh. To se da pomoje uredit z `vue-router` https://router.vuejs.org/guide/advanced/scroll-behavior.html

**Comment by joahim** [comment]
<img width="437" alt="Screenshot 2020-03-27 at 10 48 36" src="https://user-images.githubusercontent.com/1205595/77743544-8a4c3e80-7018-11ea-8e04-7b7b8ac02288.png">

**Comment by overlordtm** [comment]
Popravljeno, vsebina je bila diretno v `row`, namesto v `col-12`
