### ISSUE TITLE
UX 4 - prilagoditev velikosti grafov za 13,3'

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#61]
Prilagoditev za desktop/laptop: grafe zmanjšamo toliko, da graf z naslovom in kontrolami lahko prite v brskalnik na 13" laptopu, pri tem da je prostor spodaj za Dock/Taskbar (vem da mi geeki imamo to ob strani ali na autohide)

**Comment by joahim** [comment]
Zmanjšal na 450x. Bi moralo zadoščati.
