### ISSUE TITLE
Graf - Potrjeno okuženi po starostnih skupinah

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#68]
- labela on_hover: 5-14    --->    Starostna skupina: 5-14
- V labeli osi X bi dodal kumulativne vrednosti (VSI SUM, Ž SUM, M SUM)
- V labeli osi X in v labeli on_hover bi dodal odstotne vrednosti (%VSI, %Ž, %M)

https://ibb.co/NW0GWvy

**Comment by matejmeglic** [comment]
SUM = TOTAL

**Comment by mitjapotocin** [comment]
Bi potem kar odstranili tab "Ne glede na spol"?

![image](https://user-images.githubusercontent.com/36345162/77849542-af81ae00-71cc-11ea-8ec8-284e4ff0c551.png)

**Comment by matejmeglic** [comment]
@lukarenko @pkese a nismo to 2 dni nazaj dodali?

**Comment by lukarenko** [comment]
Ja, ker je graf bil raztegnejen. Zakaj smo šli to spreminjat? @matejmeglic

**Comment by matejmeglic** [comment]
ne vem, mislim da je @pkese to naredil zato, da bi s staro tehnologijo (ki jo je včeraj zamenjal) lažje doprinesel kumulativne vrednosti, pa ni šlo (ker je tist xyzchart.js podpiral samo prikazovanje column_name in row_name brez dodatkov).

**Comment by lukarenko** [comment]
Mene je bolj motilo, da je skupaj raztegnil graf, ampak se mi ne zdi tako pomembno, če druge ne moti

**Comment by lukarenko** [comment]
@matejmeglic jaz bi tole zaprl in raje odprl nov issue, če je še kaj za spremenit.
