### ISSUE TITLE
Popravek labele na grafu - dodajanje besede Datum:

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#70]
Na grafih:
- Širjenje COVID-19 v Sloveniji
- Obravnava hospitaliziranih
- Potrjeno okuženi po regijah

na on_hover tabeli dodati besedo **Datum:** pred DD.MM. 

https://ibb.co/5GNYJHh

**Comment by lukarenko** [comment]
@matejmeglic a je to še relevantno - zdaj imamo drugačen tooltip in je datum obširen in jasen.

**Comment by matejmeglic** [comment]
Ni, zapiram.
