### ISSUE TITLE
Na grafih označiti "statične" momente = F1-F2-F3 faze ter uvedbo ukrepov, (in, sčasoma, če bo potrebno - in upam, da ne bo - št intenzivnih postelj/ventilatorjev ipd.)

### ISSUE THREAD

**Issue by matejmeglic** [slo-covid-19/website#71]
- tukaj potrebujemo še posvet, kaj sploh prikazati in ali rabimo voditi neko tabelo teh eventov. @lukarenko

**Comment by mkadunc** [comment]
Moje mnenje o pomembnih stvareh, ki so za pokazat:
- na vseh grafih, kjer casovna os vkljucuje 20.3: ukrepi v drzavi (stopnjevanje pocasi od ~6.3. do 13.3 potem hitreje do 20.3 : to se lahko prikaze z nekim gradiranim shadingom v ozadju grafa, in povezavo na timeline izolacijskih ukrepov)
- na vseh grafih, kjer kazemo teste in potrjene: sprememba protokola za testiranje in porocanje F1->F2 in F2->F3 - ceprav je sprememba v trenutku, se vpliv pozna se na podatkih naslednjega dne, ampak bo verjetno konfuzno ce risemo sirok pas tako da je OK tudi vertikalna crta (ce je graf s podatki prekinjen, lahko pojasnilo naredimo s call-out anotacijo, sicer rabimo vertikalno crto na ozadju grafa)
- na vseh grafih, kjer kazemo hospitalizirane bi morali za 13.3. dodat anotacijo, da se je spremenil protokol hospitalizacije - prej so sprejemali vse resne, potem so jih precej posiljali domov na okrevanje (ta je lahko hkrati z anotacijo prehoda F1->F2)
- takrat, ko se je spremenil presečni čas poročanja, bi morali označit in pojasnit, da je skok zaradi (spet) spremembe protokola. Če bo vlada za nazaj popravljala podatke (verjetno ne) potem tega ne bo treba...

**Comment by mkadunc** [comment]
Prva verzija markerjev (na hitro):
13.3. F2 - nov režim testiranja in hospitalizacije, začetek stopnjevanja izolacije
20.3. F3 - nov režim testiranja, konec stopnjevanja izolacije
