### ISSUE TITLE
Tabele: Ime regije potegni iz dictionary

### ISSUE THREAD

**Issue by lukarenko** [slo-covid-19/website#96]
![image](https://user-images.githubusercontent.com/46861689/78032439-4b462200-7365-11ea-98c1-48a0ed4178a7.png)

Slovarji so v CSV tukaj, pa si ga lahko noter potegneš ali daš v neko skiupno kodo, če še ni.

https://github.com/slo-covid-19/data/tree/master/csv

**Comment by matejmeglic** [comment]
Dodaš še stolpec Tujci
